"""Add price column to cryptocurrencies

Revision ID: 50482eafe317
Revises: 58a9a4d81d12
Create Date: 2025-01-23 12:48:09.490736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50482eafe317'
down_revision: Union[str, None] = '58a9a4d81d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptocurrencies', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptocurrencies', 'price')
    # ### end Alembic commands ###
